on:
    pull_request:

jobs:
    check_branch:
         runs-on: ubuntu-latest
         steps:
            - name: Check branch
              if: github.base_ref == 'main' && github.head_ref != 'develop'
              run: | 
                echo "ERROR: Can't merge directly to main branch. Please use develop branch."
                exit 1