on: 
    pull_request:
    push:
      branches: 
      [ main ]
         
jobs:
    run_tests_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
         npm intsall
         npm run test-component

      - name: Deploy

        if: github.ref == 'refs/heads/main'
        env:
        deploy_url: ${{ secrets.MAIN_DEPLOY_HOOK_URL }}
        run: 
         curl "$deploy_url"